directories:
  - /consul
  - /consul/logs
  - /consul/scripts

files:
  - src: "docker"
    dest: "/consul"
    mode: "0744"
  - src: "mem.sh"
    dest: "/consul/scripts/mem.sh"
    mode: "0755"
  - src: "disk.sh"
    dest: "/consul/scripts/disk.sh"
    mode: "0755"

templates:
  - src: "docker-compose-agent.yml.j2"
    dest: "/consul/docker/docker-compose-agent.yml"
    mode: "0644"
  - src: "consul_check.json.j2"
    dest: "/consul/scripts/consul_check.json"
    mode: "0644"
  - src: "redeploy_service.sh.j2"
    dest: "/consul/scripts/redeploy_service.sh"
    mode: "0755"
